#!/bin/bash

if [ $2 == 'ddavis' ]; then
    USER='dougphy'
elif [ $2 == 'vgenty' ]; then
    USER='vgenty'
else
    echo 'ddavis or vgenty'
fi

REPO=$3

if [ $1 == '-h' ]; then
    git clone http://github.com/$USER/$REPO.git
elif [ $1 == '-s' ]; then
    git clone git@github.com:$USER/$REPO.git
else
    echo mygit -h [user] [repo] :: for http clone
    echo mygit -s [user] [repo] :: for ssh clone
fi
